apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-aqxu
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0083-tenant/ci10t-786-0083-app/devfile-sample-aqxu@sha256:476b25dcf84ca09b9e98178597f27e41e0323e19a35bfbf46c822b5b4aa6bb8f
        name: my-nodejs
        resources: {}
status: {}
